name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test-analyze:
    name: Lint, Test, and Sonar Analysis
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # 1. Checkout the code
      - uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run Linter
      - name: Run Linter
        run: npm run lint

      # 5. Run Format
      - name: Run Format
        run: npm run format

      # 6. Run Unit Test
      - name: Run Tests
        run: npm run test:unit
