name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint-test-analyze:
    name: Lint, Test, and Sonar Analysis
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # 1. Checkout the code
      - uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # 3. Install dependencies with Yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4. Run Linter
      - name: Run Linter
        run: yarn lint

      # 5. Run Format
      - name: Run Format
        run: yarn format

      # 6. Run Tests
      - name: Run Unit Tests
        run: yarn test:unit
